title: born in the woods
description: >-
  brain dump

author: halcyon7
email: h7-v@proton.me

theme: minima

# This forces every post to be generated at /blog/post-name
permalink: /blog/:title/

plugins:
  - jekyll-feed
